In [47]:
#Step1:downloaded dataset from the website

In [48]:
#Step2:Opened Jupyter Notebook and created (KPI_Data_Quality.ipynb) file

In [49]:
#Step3:Libraries install/import
import pandas as pd
import numpy as np
from datetime import datetime

In [50]:
# Step4: Raw dataset loading
import pandas as pd
orders = pd.read_csv(r"C:\Users\HP\OneDrive\Desktop\Retail_KPI_Project\data\retail-orders-raw.csv")
orders.head()

,order_id,order_date,customer_segment,city,category,quantity,unit_price,discount_pct,payment_status
0,RT-1001,2026-01-03,Student,Chennai,Learning Kit,2,799,10.0,Paid
1,RT-1002,03/01/2026,Fresher,Bengaluru,Course Access,1,1499,0.0,paid
2,RT-1003,2026-01-05,student,Chennai,Course Access,1,1499,NaN,Pending
3,RT-1004,2026-01-07,Professional,Hyderabad,Learning Kit,3,799,5.0,Paid
4,RT-1004,2026-01-07,Professional,Hyderabad,Learning Kit,3,799,5.0,Paid

In [51]:
 # Step5: Dataset basic information
print("Rows:", orders.shape[0])
print("Columns:", orders.shape[1])

Rows: 12
Columns: 9

In [4]:
orders.columns.tolist()

['order_id',
 'order_date',
 'customer_segment',
 'city',
 'category',
 'quantity',
 'unit_price',
 'discount_pct',
 'payment_status']

In [52]:
 # Step6 : Data Types checking
orders.dtypes

order_id             object
order_date           object
customer_segment     object
city                 object
category             object
quantity             object
unit_price            int64
discount_pct        float64
payment_status       object
dtype: object

In [53]:
 # Step7 :Retail Data Dictionary Loading
dictionary = pd.read_csv(r"C:\Users\HP\OneDrive\Desktop\Retail_KPI_Project\data\retail-data-dictionary.csv")
dictionary.head()

,column,data_type,business_definition,quality_rule
0,order_id,string,Unique order identifier,Required and unique
1,order_date,date,Date the customer placed the order,Required ISO date between 2025-01-01 and today
2,customer_segment,category,Commercial customer segment,Student Fresher or Professional after normaliz...
3,city,string,Customer billing city,Required non-empty text
4,category,category,Product family,Learning Kit Course Access or Mentor Session

In [8]:
#Full data
dictionary

,column,data_type,business_definition,quality_rule
0,order_id,string,Unique order identifier,Required and unique
1,order_date,date,Date the customer placed the order,Required ISO date between 2025-01-01 and today
2,customer_segment,category,Commercial customer segment,Student Fresher or Professional after normaliz...
3,city,string,Customer billing city,Required non-empty text
4,category,category,Product family,Learning Kit Course Access or Mentor Session
5,quantity,integer,Units purchased,Whole number greater than zero
6,unit_price,decimal,Price per unit before discount,Non-negative INR amount
7,discount_pct,decimal,Percentage discount applied,Between 0 and 100; missing means zero only aft...
8,payment_status,category,Latest order settlement state,Paid Pending Failed or Refunded after normaliz...

In [54]:
 #Step8: Dta dictionary columns
dictionary.columns.tolist()

['column', 'data_type', 'business_definition', 'quality_rule']

In [10]:
dictionary.shape

(9, 4)

In [11]:
dictionary.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9 entries, 0 to 8
Data columns (total 4 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   column               9 non-null      object
 1   data_type            9 non-null      object
 2   business_definition  9 non-null      object
 3   quality_rule         9 non-null      object
dtypes: object(4)
memory usage: 420.0+ bytes

In [55]:
# Step9 :Dataset Profiling
orders.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12 entries, 0 to 11
Data columns (total 9 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   order_id          12 non-null     object
 1   order_date        11 non-null     object
 2   customer_segment  12 non-null     object
 3   city              11 non-null     object
 4   category          12 non-null     object
 5   quantity          12 non-null     object
 6   unit_price        12 non-null     int64
 7   discount_pct      11 non-null     float64
 8   payment_status    12 non-null     object
dtypes: float64(1), int64(1), object(7)
memory usage: 996.0+ bytes

In [14]:
orders.describe(include="all")

,order_id,order_date,customer_segment,city,category,quantity,unit_price,discount_pct,payment_status
count,12,11,12,11,12,12,12.000000,11.000000,12
unique,11,10,4,7,3,5,NaN,NaN,5
top,RT-1004,2026-01-07,Student,Chennai,Learning Kit,1,NaN,NaN,Paid
freq,2,2,4,3,5,5,NaN,NaN,7
mean,NaN,NaN,NaN,NaN,NaN,NaN,1082.333333,13.636364,NaN
std,NaN,NaN,NaN,NaN,NaN,NaN,318.614425,30.748245,NaN
min,NaN,NaN,NaN,NaN,NaN,NaN,799.000000,0.000000,NaN
25%,NaN,NaN,NaN,NaN,NaN,NaN,799.000000,0.000000,NaN
50%,NaN,NaN,NaN,NaN,NaN,NaN,999.000000,5.000000,NaN
75%,NaN,NaN,NaN,NaN,NaN,NaN,1499.000000,10.000000,NaN
max,NaN,NaN,NaN,NaN,NaN,NaN,1499.000000,105.000000,NaN

In [15]:
#Numeric Columns
orders.describe()

        unit_price  discount_pct
count    12.000000     11.000000
mean   1082.333333     13.636364
std     318.614425     30.748245
min     799.000000      0.000000
25%     799.000000      0.000000
50%     999.000000      5.000000
75%    1499.000000     10.000000
max    1499.000000    105.000000

In [56]:
# Step10 : Missing Values/Completeness
orders.isna().sum()

order_id            0
order_date          1
customer_segment    0
city                1
category            0
quantity            0
unit_price          0
discount_pct        1
payment_status      0
dtype: int64

In [17]:
#Percentage Calculation
missing_count = orders.isna().sum()
missing_percent = (missing_count / len(orders)) * 100
missing_profile = pd.DataFrame({
    "Missing Count": missing_count,
    "Missing %": missing_percent
})
missing_profile

                  Missing Count  Missing %
order_id                      0   0.000000
order_date                    1   8.333333
customer_segment              0   0.000000
city                          1   8.333333
category                      0   0.000000
quantity                      0   0.000000
unit_price                    0   0.000000
discount_pct                  1   8.333333
payment_status                0   0.000000

In [18]:
#Overall Completeness
#completeness formula----->(Completeness % =(Number of non-null values / Total values) × 100)

overall_completeness = (
    orders.notna().sum().sum() /
    orders.size
) * 100

overall_completeness

97.22222222222221

In [57]:
# Step 11 :Uniqueness Check

#  duplicate rows 
orders.duplicated().sum()

#Duplicate Percentage
duplicate_percent = (
    orders.duplicated().sum() / len(orders)
) * 100

duplicate_percent

8.333333333333332

In [22]:
#important ID column
orders["order_id"].nunique()

11

In [24]:
orders["order_id"].duplicated().sum()

1

In [58]:
# Step 12: Validity Check
# check Quality
orders["quantity"].describe()

count     12
unique     5
top        1
freq       5
Name: quantity, dtype: object

In [36]:
#checking quantity datatype
orders["quantity"].dtype

dtype('float64')

In [37]:
#data Present in Quantity
orders["quantity"].head(10)

0    2.0
1    1.0
2    1.0
3    3.0
4    3.0
5    1.0
6   -1.0
7    2.0
8    NaN
9    1.0
Name: quantity, dtype: float64

In [33]:
orders["quantity"].apply(type).value_counts()

quantity
<class 'str'>    12
Name: count, dtype: int64

In [39]:
#Convert quantity to numeric
orders["quantity"] = pd.to_numeric(orders["quantity"], errors="coerce")

In [40]:
#Check negative quantities
(orders["quantity"] < 0).sum()

1

In [41]:
#Check Zero quantities
(orders["quantity"] == 0).sum()

0

In [42]:
#Check unit_price
orders["unit_price"].describe()

count      12.000000
mean     1082.333333
std       318.614425
min       799.000000
25%       799.000000
50%       999.000000
75%      1499.000000
max      1499.000000
Name: unit_price, dtype: float64

In [43]:
#check Negative Prices
(orders["unit_price"] < 0).sum()

0

In [44]:
#Zero Prices
(orders["unit_price"] == 0).sum()

0

In [45]:
#check discount_pct
orders["discount_pct"].describe()

count     11.000000
mean      13.636364
std       30.748245
min        0.000000
25%        0.000000
50%        5.000000
75%       10.000000
max      105.000000
Name: discount_pct, dtype: float64

In [46]:
#Invalid discounts
((orders["discount_pct"] < 0) | 
 (orders["discount_pct"] > 100)).sum()

1

In [59]:
# Step13: check payyment_statue
orders["payment_status"].value_counts(dropna=False)

payment_status
Paid        7
Pending     2
paid        1
Failed      1
Refunded    1
Name: count, dtype: int64

In [60]:
#check unique values
orders["payment_status"].unique()

array(['Paid', 'paid', 'Pending', 'Failed', 'Refunded'], dtype=object)

In [61]:

valid_payment_status = [
    "Paid",
    "Pending",
    "Cancelled"
]

In [62]:
invalid_payment_status = ~orders["payment_status"].isin(valid_payment_status)

invalid_payment_status.sum()

3

In [63]:
# Step 14:Check categorical columns

#Customer segment
orders["customer_segment"].value_counts(dropna=False)

customer_segment
Student         4
Professional    4
Fresher         3
student         1
Name: count, dtype: int64

In [64]:
#City
orders["city"].value_counts(dropna=False)

city
Chennai      3
Bengaluru    2
Hyderabad    2
NaN          1
Pune         1
Mumbai       1
Delhi        1
Kochi        1
Name: count, dtype: int64

In [65]:
#Category
orders["category"].value_counts(dropna=False)

category
Learning Kit      5
Course Access     4
Mentor Session    3
Name: count, dtype: int64

In [66]:
# Step 15:Convert order_date to datetime
orders["order_date"] = pd.to_datetime(
    orders["order_date"],
    errors="coerce"
)

In [67]:
#check invalid dates
invalid_dates = orders["order_date"].isna().sum()

invalid_dates

3

In [68]:
#Check date range
print("Minimum date:", orders["order_date"].min())
print("Maximum date:", orders["order_date"].max())

Minimum date: 2026-01-03 00:00:00
Maximum date: 2026-01-18 00:00:00

In [69]:
# Step 16: Completeness Check (check missing values in all your actual columns)
missing_count = orders.isna().sum()

missing_percent = (missing_count / len(orders)) * 100

completeness_profile = pd.DataFrame({
    "Missing Count": missing_count,
    "Missing %": missing_percent,
    "Completeness %": 100 - missing_percent
})

completeness_profile

                  Missing Count  Missing %  Completeness %
order_id                      0   0.000000      100.000000
order_date                    3  25.000000       75.000000
customer_segment              0   0.000000      100.000000
city                          1   8.333333       91.666667
category                      0   0.000000      100.000000
quantity                      0   0.000000      100.000000
unit_price                    0   0.000000      100.000000
discount_pct                  1   8.333333       91.666667
payment_status                0   0.000000      100.000000

In [70]:
# Step 17: Required Columns Check
required_columns = [
    "order_id",
    "order_date",
    "customer_segment",
    "city",
    "category",
    "quantity",
    "unit_price",
    "discount_pct",
    "payment_status"
]

In [71]:
missing_columns = [
    col for col in required_columns
    if col not in orders.columns
]

missing_columns

[]

In [72]:
# Step1 18: Required Fields Missing Values
required_missing = orders[required_columns].isna().sum()

required_missing

order_id            0
order_date          3
customer_segment    0
city                1
category            0
quantity            0
unit_price          0
discount_pct        1
payment_status      0
dtype: int64

In [73]:
required_missing.sum()

5

In [74]:
# STEP 19 — Uniqueness Check
orders["order_id"].nunique()

11

In [75]:
orders["order_id"].duplicated().sum()

1

In [76]:
orders["order_id"].value_counts().head(10)

order_id
RT-1004    2
RT-1001    1
RT-1002    1
RT-1003    1
RT-1005    1
RT-1006    1
RT-1007    1
RT-1008    1
RT-1009    1
RT-1010    1
Name: count, dtype: int64

In [77]:
duplicate_rows = orders.duplicated().sum()

duplicate_rows

1

In [78]:
duplicate_percent = (
    duplicate_rows / len(orders)
) * 100

duplicate_percent

8.333333333333332

In [79]:
 # STEP 20 — Consistency Check
# 20.1 Same order having multiple cities
order_city_check = orders.groupby("order_id")["city"].nunique()

multiple_cities = (order_city_check > 1).sum()

multiple_cities

0

In [81]:
# 20.2 Same order having multiple customer segments
order_segment_check = (
    orders.groupby("order_id")["customer_segment"].nunique()
)

multiple_segments = (order_segment_check > 1).sum()

multiple_segments

0

In [82]:
# 20.3 Same order having multiple dates
order_date_check = (
    orders.groupby("order_id")["order_date"].nunique()
)

multiple_dates = (order_date_check > 1).sum()

multiple_dates

0

In [84]:
# STEP 21 — Calculate Sales Because my dataset doesn't have sales, create it.

# Formula -->(Gross Sales = quantity × unit_price)

#Discount amount -->(Discount = Gross Sales × discount_pct / 100)

# Net sales --> (Net Sales = Gross Sales - Discount)

orders["gross_sales"] = (
    orders["quantity"] * orders["unit_price"]
)

In [86]:
orders[["gross_sales", "discount_pct"]].dtypes

gross_sales      object
discount_pct    float64
dtype: object

In [87]:
orders[["gross_sales", "discount_pct"]].head(10)

                                         gross_sales  discount_pct
0  2222222222222222222222222222222222222222222222...          10.0
1  1111111111111111111111111111111111111111111111...           0.0
2  1111111111111111111111111111111111111111111111...           NaN
3  3333333333333333333333333333333333333333333333...           5.0
4  3333333333333333333333333333333333333333333333...           5.0
5  1111111111111111111111111111111111111111111111...           0.0
6  -1-1-1-1-1-1-1-1-1-1-1-1-1-1-1-1-1-1-1-1-1-1-1...          10.0
7  2222222222222222222222222222222222222222222222...         105.0
8  twotwotwotwotwotwotwotwotwotwotwotwotwotwotwot...           0.0
9  1111111111111111111111111111111111111111111111...           0.0

In [88]:
# Convert them to numeric
orders["gross_sales"] = pd.to_numeric(
    orders["gross_sales"],
    errors="coerce"
)

orders["discount_pct"] = pd.to_numeric(
    orders["discount_pct"],
    errors="coerce"
)

In [89]:
orders[["gross_sales", "discount_pct"]].dtypes

gross_sales     float64
discount_pct    float64
dtype: object

In [91]:
orders["discount_amount"] = (
    orders["gross_sales"] *
    orders["discount_pct"] / 100
)

In [92]:
orders["net_sales"] = (
    orders["gross_sales"] -
    orders["discount_amount"]
)

In [93]:
orders[
    [
        "quantity",
        "unit_price",
        "discount_pct",
        "gross_sales",
        "discount_amount",
        "net_sales"
    ]
].head()

  quantity  unit_price  discount_pct  gross_sales  discount_amount  net_sales
0        2         799          10.0          NaN              NaN        NaN
1        1        1499           0.0          NaN              NaN        NaN
2        1        1499           NaN          NaN              NaN        NaN
3        3         799           5.0          NaN              NaN        NaN
4        3         799           5.0          NaN              NaN        NaN

In [94]:
# STEP 22 — Validate Calculated Sales
#check Negative net sales
negative_net_sales = (
    orders["net_sales"] < 0
).sum()

negative_net_sales

0

In [96]:
# First convert quantity to numeric:
orders["quantity"] = pd.to_numeric(
    orders["quantity"],
    errors="coerce"
)

In [97]:
#check Negative quantity
negative_quantity = (
    orders["quantity"] < 0
).sum()

negative_quantity

1

In [98]:
#Check invalid discount:
invalid_discount = (
    (orders["discount_pct"] < 0) |
    (orders["discount_pct"] > 100)
).sum()

invalid_discount

1

In [99]:
# STEP 23 — Freshness Check
#Find latest order
latest_order_date = orders["order_date"].max()

latest_order_date

Timestamp('2026-01-18 00:00:00')

In [100]:
# Find earliest
earliest_order_date = orders["order_date"].min()

earliest_order_date

Timestamp('2026-01-03 00:00:00')

In [101]:
# Data age
today = pd.Timestamp.today().normalize()

data_age_days = (
    today - latest_order_date
).days

data_age_days

242

In [102]:
# STEP 24 — Create Complete Data Quality Profile
# combine everything
quality_profile = pd.DataFrame({
    "Dimension": [
        "Completeness",
        "Uniqueness",
        "Validity - Dates",
        "Validity - Quantity",
        "Validity - Unit Price",
        "Validity - Discount",
        "Consistency - City",
        "Consistency - Customer Segment",
        "Consistency - Order Date",
        "Freshness"
    ],
    
    "Metric": [
        "Missing required values",
        "Exact duplicate rows",
        "Invalid dates",
        "Negative quantity",
        "Negative unit price",
        "Invalid discount %",
        "Orders with multiple cities",
        "Orders with multiple customer segments",
        "Orders with multiple dates",
        "Data age in days"
    ],
    
    "Result": [
        required_missing.sum(),
        duplicate_rows,
        invalid_dates,
        negative_quantity,
        (orders["unit_price"] < 0).sum(),
        invalid_discount,
        multiple_cities,
        multiple_segments,
        multiple_dates,
        data_age_days
    ]
})

quality_profile

,Dimension,Metric,Result
0,Completeness,Missing required values,5
1,Uniqueness,Exact duplicate rows,1
2,Validity - Dates,Invalid dates,3
3,Validity - Quantity,Negative quantity,1
4,Validity - Unit Price,Negative unit price,0
5,Validity - Discount,Invalid discount %,1
6,Consistency - City,Orders with multiple cities,0
7,Consistency - Customer Segment,Orders with multiple customer segments,0
8,Consistency - Order Date,Orders with multiple dates,0
9,Freshness,Data age in days,242

In [103]:
# STEP 25 — Add PASS / FAIL
# create thresholds

quality_profile["Threshold"] = [
    0,  # completeness
    0,  # duplicates
    0,  # invalid dates
    0,  # negative quantity
    0,  # negative price
    0,  # invalid discount
    0,  # multiple cities
    0,  # multiple segments
    0,  # multiple dates
    1   # freshness
]

In [104]:
quality_profile["Status"] = np.where(
    quality_profile["Result"] <= quality_profile["Threshold"],
    "PASS",
    "FAIL"
)

In [105]:
quality_profile

,Dimension,Metric,Result,Threshold,Status
0,Completeness,Missing required values,5,0,FAIL
1,Uniqueness,Exact duplicate rows,1,0,FAIL
2,Validity - Dates,Invalid dates,3,0,FAIL
3,Validity - Quantity,Negative quantity,1,0,FAIL
4,Validity - Unit Price,Negative unit price,0,0,PASS
5,Validity - Discount,Invalid discount %,1,0,FAIL
6,Consistency - City,Orders with multiple cities,0,0,PASS
7,Consistency - Customer Segment,Orders with multiple customer segments,0,0,PASS
8,Consistency - Order Date,Orders with multiple dates,0,0,PASS
9,Freshness,Data age in days,242,1,FAIL

In [106]:
# Freshness caveat
#Actual data age <= allowed threshold → PASS
#Actual data age > allowed threshold → FAIL

In [107]:
# STEP 26 — KPI #1 Total Sales

total_sales = orders["net_sales"].sum()

total_sales

0.0

In [108]:
# STEP 27 — KPI #2 Total Orders

total_orders = orders["order_id"].nunique()

total_orders

11

In [109]:
# STEP 28 — KPI #3 Total Customers
      #Orders by Customer Segment
orders_by_segment = (
    orders.groupby("customer_segment")["order_id"]
    .nunique()
)

orders_by_segment

customer_segment
Fresher         3
Professional    3
Student         4
student         1
Name: order_id, dtype: int64

In [110]:
# STEP 29 —  8 KPIs(We need at least 8 KPIs, so let's define KPIs that are actually supported by my data.)

# KPI 1 — Total Net Sales
total_net_sales = orders["net_sales"].sum()

In [111]:
# KPI 2 — Total Orders
total_orders = orders["order_id"].nunique()

In [112]:
# KPI 3 — Total Quantity Sold
total_quantity = orders["quantity"].sum()

In [113]:
# KPI 4 — Average Order Value
average_order_value = (total_net_sales / total_orders)

In [114]:
# KPI 5 — Average Unit Price
average_unit_price = orders["unit_price"].mean()

In [115]:
# KPI 6 — Average Discount %
average_discount = orders["discount_pct"].mean()

In [116]:
# KPI 7 — Paid Order Rate
paid_orders = orders.loc[
    orders["payment_status"] == "Paid",
    "order_id"
].nunique()

paid_order_rate = (
    paid_orders / total_orders
) * 100

paid_order_rate

54.54545454545454

In [117]:
# KPI 8 — Orders by Category
orders_by_category = (
    orders.groupby("category")["order_id"]
    .nunique()
)

orders_by_category

category
Course Access     4
Learning Kit      4
Mentor Session    3
Name: order_id, dtype: int64

In [118]:
# STEP 30 — Create KPI Results Table

kpi_results = pd.DataFrame({
    "KPI": [
        "Total Net Sales",
        "Total Orders",
        "Total Quantity Sold",
        "Average Order Value",
        "Average Unit Price",
        "Average Discount %",
        "Paid Order Rate"
    ],
    
    "Value": [
        total_net_sales,
        total_orders,
        total_quantity,
        average_order_value,
        average_unit_price,
        average_discount,
        paid_order_rate
    ]
})

kpi_results

                   KPI        Value
0      Total Net Sales     0.000000
1         Total Orders    11.000000
2  Total Quantity Sold    16.000000
3  Average Order Value     0.000000
4   Average Unit Price  1082.333333
5   Average Discount %    13.636364
6      Paid Order Rate    54.545455

In [119]:
# For the 8th, use Category Order Count as a grouped KPI:

category_kpi = (
    orders.groupby("category")
    .agg(
        orders=("order_id", "nunique"),
        net_sales=("net_sales", "sum"),
        quantity=("quantity", "sum")
    )
    .reset_index()
)

category_kpi

         category  orders  net_sales  quantity
0   Course Access       4        0.0       4.0
1    Learning Kit       4        0.0       8.0
2  Mentor Session       3        0.0       4.0

In [120]:
# STEP 31 — KPI Dictionary

kpi_dictionary = pd.DataFrame({
    "KPI Name": [
        "Total Net Sales",
        "Total Orders",
        "Total Quantity Sold",
        "Average Order Value",
        "Average Unit Price",
        "Average Discount %",
        "Paid Order Rate",
        "Category Net Sales"
    ],
    
    "Business Definition": [
        "Total revenue after applying order-level discounts.",
        "Number of distinct retail orders.",
        "Total quantity of items sold.",
        "Average net sales value per order.",
        "Average listed unit price across order lines.",
        "Average discount percentage applied to order lines.",
        "Percentage of distinct orders with Paid payment status.",
        "Net sales generated by each product category."
    ],
    
    "Formula": [
        "SUM(quantity × unit_price × (1 - discount_pct/100))",
        "COUNT DISTINCT(order_id)",
        "SUM(quantity)",
        "Total Net Sales / Total Orders",
        "AVG(unit_price)",
        "AVG(discount_pct)",
        "Paid Orders / Total Orders × 100",
        "SUM(net_sales) GROUP BY category"
    ],
    
    "Grain": [
        "Overall / Monthly",
        "Overall / Monthly",
        "Overall / Monthly",
        "Overall / Monthly",
        "Overall / Monthly",
        "Overall / Monthly",
        "Overall / Monthly",
        "Category / Monthly"
    ],
    
    "Filters": [
        "Valid quantity, price and discount",
        "Valid order_id",
        "Valid quantity",
        "Valid order_id and net_sales",
        "Valid unit_price",
        "Valid discount_pct",
        "Valid order_id and payment_status",
        "Valid category and net_sales"
    ],
    
    "Owner": [
        "Sales Manager",
        "Operations Manager",
        "Operations Manager",
        "Sales Manager",
        "Pricing Manager",
        "Pricing Manager",
        "Finance Manager",
        "Category Manager"
    ],
    
    "Refresh Cadence": [
        "Daily",
        "Daily",
        "Daily",
        "Daily",
        "Daily",
        "Daily",
        "Daily",
        "Daily"
    ]
})

kpi_dictionary

,KPI Name,Business Definition,Formula,Grain,Filters,Owner,Refresh Cadence
0,Total Net Sales,Total revenue after applying order-level disco...,SUM(quantity × unit_price × (1 - discount_pct/...,Overall / Monthly,"Valid quantity, price and discount",Sales Manager,Daily
1,Total Orders,Number of distinct retail orders.,COUNT DISTINCT(order_id),Overall / Monthly,Valid order_id,Operations Manager,Daily
2,Total Quantity Sold,Total quantity of items sold.,SUM(quantity),Overall / Monthly,Valid quantity,Operations Manager,Daily
3,Average Order Value,Average net sales value per order.,Total Net Sales / Total Orders,Overall / Monthly,Valid order_id and net_sales,Sales Manager,Daily
4,Average Unit Price,Average listed unit price across order lines.,AVG(unit_price),Overall / Monthly,Valid unit_price,Pricing Manager,Daily
5,Average Discount %,Average discount percentage applied to order l...,AVG(discount_pct),Overall / Monthly,Valid discount_pct,Pricing Manager,Daily
6,Paid Order Rate,Percentage of distinct orders with Paid paymen...,Paid Orders / Total Orders × 100,Overall / Monthly,Valid order_id and payment_status,Finance Manager,Daily
7,Category Net Sales,Net sales generated by each product category.,SUM(net_sales) GROUP BY category,Category / Monthly,Valid category and net_sales,Category Manager,Daily

In [122]:
# STEP 32 — Export KPI Dictionary
kpi_dictionary.to_excel(
    "KPI_Dictionary.xlsx",
    index=False
)

In [123]:
# STEP 33 — Export Data Quality Profile

quality_profile.to_excel(
    "Data_Quality_Profile.xlsx",
    index=False
)

In [124]:
# STEP 34 — Create Data Quality Contract

quality_contract = pd.DataFrame({
    "Dimension": [
        "Completeness",
        "Uniqueness",
        "Validity",
        "Validity",
        "Validity",
        "Consistency",
        "Consistency",
        "Freshness"
    ],
    
    "Rule": [
        "Required columns must not contain missing values.",
        "Exact duplicate rows must not exist.",
        "Order dates must be valid.",
        "Quantity must be zero or greater.",
        "Discount percentage must be between 0 and 100.",
        "An order should not have multiple cities.",
        "An order should not have multiple customer segments.",
        "Data must be refreshed within the agreed freshness window."
    ],
    
    "Threshold": [
        "0% missing",
        "0 duplicate rows",
        "0 invalid dates",
        "0 negative quantities",
        "0 invalid discounts",
        "0 inconsistent orders",
        "0 inconsistent orders",
        "≤ 1 day"
    ],
    
    "Failure Action": [
        "Block KPI publication and investigate source.",
        "Remove/quarantine duplicates and investigate source.",
        "Quarantine invalid records and investigate.",
        "Quarantine invalid records.",
        "Quarantine invalid records.",
        "Investigate source-system inconsistency.",
        "Investigate source-system inconsistency.",
        "Escalate to data owner and delay dashboard refresh."
    ],
    
    "Owner": [
        "Data Engineering",
        "Data Engineering",
        "Data Engineering",
        "Data Engineering",
        "Data Engineering",
        "Operations",
        "Operations",
        "Data Engineering"
    ]
})

quality_contract

,Dimension,Rule,Threshold,Failure Action,Owner
0,Completeness,Required columns must not contain missing values.,0% missing,Block KPI publication and investigate source.,Data Engineering
1,Uniqueness,Exact duplicate rows must not exist.,0 duplicate rows,Remove/quarantine duplicates and investigate s...,Data Engineering
2,Validity,Order dates must be valid.,0 invalid dates,Quarantine invalid records and investigate.,Data Engineering
3,Validity,Quantity must be zero or greater.,0 negative quantities,Quarantine invalid records.,Data Engineering
4,Validity,Discount percentage must be between 0 and 100.,0 invalid discounts,Quarantine invalid records.,Data Engineering
5,Consistency,An order should not have multiple cities.,0 inconsistent orders,Investigate source-system inconsistency.,Operations
6,Consistency,An order should not have multiple customer seg...,0 inconsistent orders,Investigate source-system inconsistency.,Operations
7,Freshness,Data must be refreshed within the agreed fresh...,≤ 1 day,Escalate to data owner and delay dashboard ref...,Data Engineering

In [125]:
# STEP 35 — Export Contract

quality_contract.to_excel(
    "Data_Quality_Contract.xlsx",
    index=False
)